version: '3.8'

services:

  reverse-proxy:
    build:
      context: ./nginx
    ports:
      - "80:80"
  
  nodeserver:
    build:
      context: ./app
    ports:
      - "3000:8080"

# to run, docker-compose up --build
# navigate to localhost:3000 to view html